import { Doctor, Appointment, PatientProfile } from './types';

export const mockDoctors: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Sarah Mitchell',
    email: 'sarah.mitchell@medilink.com',
    phone: '+1 (555) 234-5678',
    specialization: 'Cardiology',
    experience: 12,
    qualifications: 'MD, FACC – Harvard Medical School',
    hospital: "St. Mary's Medical Center",
    clinic: 'Mitchell Heart Clinic',
    location: 'New York, NY',
    consultationFee: 150,
    bio: "Dr. Mitchell is a board-certified cardiologist with over 12 years of experience treating complex cardiovascular conditions. She specializes in preventive cardiology, heart failure management, and advanced cardiac imaging. She has been recognized for her compassionate patient-centered approach.",
    rating: 4.9,
    reviewCount: 247,
    availability: {
      Monday: { start: '09:00', end: '13:00' },
      Tuesday: { start: '14:00', end: '18:00' },
      Wednesday: { start: '09:00', end: '13:00' },
      Thursday: { start: '14:00', end: '18:00' },
      Friday: { start: '09:00', end: '12:00' },
      Saturday: null,
      Sunday: null,
    },
  },
  {
    id: 'd2',
    name: 'Dr. James Chen',
    email: 'james.chen@medilink.com',
    phone: '+1 (555) 345-6789',
    specialization: 'Neurology',
    experience: 15,
    qualifications: 'MD, PhD – Johns Hopkins School of Medicine',
    hospital: 'City General Hospital',
    clinic: 'Chen Neuroscience Center',
    location: 'Boston, MA',
    consultationFee: 200,
    bio: 'Dr. Chen is a distinguished neurologist specializing in epilepsy, movement disorders, and headache medicine. He completed his neurology residency and fellowship at Johns Hopkins and has published over 40 peer-reviewed papers in leading journals.',
    rating: 4.8,
    reviewCount: 189,
    availability: {
      Monday: { start: '10:00', end: '14:00' },
      Tuesday: null,
      Wednesday: { start: '10:00', end: '14:00' },
      Thursday: { start: '15:00', end: '19:00' },
      Friday: { start: '10:00', end: '14:00' },
      Saturday: { start: '09:00', end: '12:00' },
      Sunday: null,
    },
  },
  {
    id: 'd3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@medilink.com',
    phone: '+1 (555) 456-7890',
    specialization: 'General Practice',
    experience: 8,
    qualifications: 'MD, MRCGP – Columbia University',
    hospital: 'Riverside Community Health',
    clinic: 'Rodriguez Family Clinic',
    location: 'Chicago, IL',
    consultationFee: 80,
    bio: 'Dr. Rodriguez is a passionate family medicine physician dedicated to comprehensive primary care for patients of all ages. She emphasizes preventive medicine, chronic disease management, and building long-term relationships with her patients.',
    rating: 4.7,
    reviewCount: 312,
    availability: {
      Monday: { start: '08:00', end: '16:00' },
      Tuesday: { start: '08:00', end: '16:00' },
      Wednesday: { start: '08:00', end: '16:00' },
      Thursday: { start: '08:00', end: '16:00' },
      Friday: { start: '08:00', end: '14:00' },
      Saturday: { start: '09:00', end: '12:00' },
      Sunday: null,
    },
  },
  {
    id: 'd4',
    name: 'Dr. Michael Thompson',
    email: 'michael.thompson@medilink.com',
    phone: '+1 (555) 567-8901',
    specialization: 'Orthopedic Surgery',
    experience: 18,
    qualifications: 'MD, FAAOS – Stanford Medical School',
    hospital: 'Summit Orthopedic Hospital',
    clinic: 'Thompson Sports Medicine',
    location: 'San Francisco, CA',
    consultationFee: 220,
    bio: 'Dr. Thompson is a highly skilled orthopedic surgeon with 18 years of experience in joint replacement, sports medicine, and complex fracture management. He has treated professional athletes and is recognized for his minimally invasive surgical expertise.',
    rating: 4.9,
    reviewCount: 156,
    availability: {
      Monday: { start: '07:00', end: '12:00' },
      Tuesday: { start: '13:00', end: '18:00' },
      Wednesday: { start: '07:00', end: '12:00' },
      Thursday: { start: '13:00', end: '18:00' },
      Friday: null,
      Saturday: null,
      Sunday: null,
    },
  },
  {
    id: 'd5',
    name: 'Dr. Priya Patel',
    email: 'priya.patel@medilink.com',
    phone: '+1 (555) 678-9012',
    specialization: 'Dermatology',
    experience: 10,
    qualifications: 'MD, FAAD – University of Pennsylvania',
    hospital: 'Dermatology Associates',
    clinic: 'Clear Skin Clinic',
    location: 'Los Angeles, CA',
    consultationFee: 120,
    bio: 'Dr. Patel is an experienced dermatologist specializing in medical and cosmetic dermatology. She has particular expertise in skin cancer screening, acne management, eczema treatment, and cosmetic dermatology procedures.',
    rating: 4.8,
    reviewCount: 278,
    availability: {
      Monday: { start: '09:00', end: '17:00' },
      Tuesday: { start: '09:00', end: '17:00' },
      Wednesday: null,
      Thursday: { start: '09:00', end: '17:00' },
      Friday: { start: '09:00', end: '15:00' },
      Saturday: { start: '10:00', end: '13:00' },
      Sunday: null,
    },
  },
  {
    id: 'd6',
    name: 'Dr. David Kim',
    email: 'david.kim@medilink.com',
    phone: '+1 (555) 789-0123',
    specialization: 'Pediatrics',
    experience: 9,
    qualifications: 'MD, FAAP – Yale School of Medicine',
    hospital: "Children's Memorial Hospital",
    clinic: 'Kim Pediatric Center',
    location: 'Seattle, WA',
    consultationFee: 100,
    bio: 'Dr. Kim is a dedicated pediatrician providing comprehensive healthcare for children from newborns through adolescents. He is known for his warm, child-friendly approach and expertise in developmental pediatrics and adolescent medicine.',
    rating: 4.9,
    reviewCount: 334,
    availability: {
      Monday: { start: '08:00', end: '16:00' },
      Tuesday: { start: '08:00', end: '16:00' },
      Wednesday: { start: '08:00', end: '16:00' },
      Thursday: { start: '08:00', end: '16:00' },
      Friday: { start: '08:00', end: '12:00' },
      Saturday: null,
      Sunday: null,
    },
  },
];

export const mockPatient: PatientProfile = {
  id: 'p1',
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  phone: '+1 (555) 123-4567',
  dateOfBirth: '1990-07-15',
  gender: 'Male',
  bloodGroup: 'O+',
  address: '123 Maple Street, New York, NY 10001',
};

export const mockPatientAppointments: Appointment[] = [
  {
    id: 'a1',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-10-05',
    time: '10:00 AM',
    status: 'confirmed',
    reason: 'Annual heart checkup and blood pressure monitoring',
  },
  {
    id: 'a2',
    doctorId: 'd3',
    doctorName: 'Dr. Emily Rodriguez',
    doctorSpecialization: 'General Practice',
    doctorHospital: 'Riverside Community Health',
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-10-12',
    time: '2:30 PM',
    status: 'pending',
    reason: 'General consultation – persistent cough and fatigue',
  },
  {
    id: 'a3',
    doctorId: 'd5',
    doctorName: 'Dr. Priya Patel',
    doctorSpecialization: 'Dermatology',
    doctorHospital: 'Dermatology Associates',
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-09-15',
    time: '11:30 AM',
    status: 'completed',
    reason: 'Skin rash evaluation and treatment plan',
  },
  {
    id: 'a4',
    doctorId: 'd4',
    doctorName: 'Dr. Michael Thompson',
    doctorSpecialization: 'Orthopedic Surgery',
    doctorHospital: 'Summit Orthopedic Hospital',
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-09-05',
    time: '9:00 AM',
    status: 'cancelled',
    reason: 'Knee pain evaluation and possible imaging',
  },
  {
    id: 'a5',
    doctorId: 'd2',
    doctorName: 'Dr. James Chen',
    doctorSpecialization: 'Neurology',
    doctorHospital: 'City General Hospital',
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-09-20',
    time: '3:00 PM',
    status: 'rejected',
    reason: 'Severe recurring headaches – neurological evaluation',
  },
];

export const mockDoctorAppointments: Appointment[] = [
  {
    id: 'da1',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p1',
    patientName: 'Alex Johnson',
    date: '2026-10-05',
    time: '10:00 AM',
    status: 'confirmed',
    reason: 'Annual heart checkup and blood pressure monitoring',
  },
  {
    id: 'da2',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p2',
    patientName: 'Maria Garcia',
    date: '2026-10-05',
    time: '11:00 AM',
    status: 'pending',
    reason: 'Chest pain and shortness of breath on exertion',
  },
  {
    id: 'da3',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p3',
    patientName: 'Robert Davis',
    date: '2026-10-05',
    time: '12:00 PM',
    status: 'pending',
    reason: 'Follow-up after cardiac catheterization',
  },
  {
    id: 'da4',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p4',
    patientName: 'Jennifer Lee',
    date: '2026-10-08',
    time: '10:30 AM',
    status: 'confirmed',
    reason: 'Atrial fibrillation management and medication review',
  },
  {
    id: 'da5',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p5',
    patientName: 'Thomas Wilson',
    date: '2026-09-25',
    time: '2:00 PM',
    status: 'completed',
    reason: 'Post-bypass surgery 6-week follow-up',
  },
  {
    id: 'da6',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Mitchell',
    doctorSpecialization: 'Cardiology',
    doctorHospital: "St. Mary's Medical Center",
    patientId: 'p6',
    patientName: 'Sarah Thompson',
    date: '2026-09-22',
    time: '3:00 PM',
    status: 'rejected',
    reason: 'Heart palpitations and occasional dizziness',
  },
];

export const specializations = [
  'Cardiology',
  'Dermatology',
  'General Practice',
  'Neurology',
  'Orthopedic Surgery',
  'Pediatrics',
  'Psychiatry',
  'Oncology',
  'Endocrinology',
  'Gastroenterology',
  'Pulmonology',
  'Rheumatology',
];

export const locations = ['New York, NY', 'Boston, MA', 'Chicago, IL', 'San Francisco, CA', 'Los Angeles, CA', 'Seattle, WA'];

export const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export function generateTimeSlots(start: string, end: string): string[] {
  const slots: string[] = [];
  const [startH, startM] = start.split(':').map(Number);
  const [endH, endM] = end.split(':').map(Number);
  let h = startH;
  let m = startM;
  while (h < endH || (h === endH && m < endM)) {
    const suffix = h < 12 ? 'AM' : 'PM';
    const displayH = h <= 12 ? h : h - 12;
    const displayM = m === 0 ? '00' : String(m);
    slots.push(`${displayH}:${displayM} ${suffix}`);
    m += 30;
    if (m >= 60) { m -= 60; h++; }
  }
  return slots;
}
